"""
GroqService — uses Groq (llama-3.1-8b-instant) for high-level reasoning ONLY.

Input:  structured facts extracted deterministically by analysis agents + Ollama
Output: project overview, detected features (with evidence), architecture notes,
        workflow steps, confidence score

The service NEVER receives raw file content or repository code.
"""
import json
import logging

from app.services.llm_service import GroqClient

logger = logging.getLogger(__name__)

# Module-level singleton — GroqClient/Groq SDK is stateless per call (no
# mutable per-request state), so sharing one instance is safe under
# concurrent async usage.
_groq_service_singleton: "GroqAnalysisService | None" = None


def get_groq_service() -> "GroqAnalysisService":
    """Return (or create) the process-wide GroqAnalysisService singleton."""
    global _groq_service_singleton
    if _groq_service_singleton is None:
        _groq_service_singleton = GroqAnalysisService()
    return _groq_service_singleton


class GroqAnalysisService:
    """Accepts a structured facts dict and returns an enriched AI analysis."""

    def __init__(self) -> None:
        self._client = GroqClient()

    def generate_report(self, facts: dict) -> dict:
        """
        facts schema:
        {
            "repository_name": str,
            "frontend": [str],
            "backend": [str],
            "databases": [str],
            "languages": [str],
            "frameworks": [str],
            "apis": [{"method": str, "path": str, "framework": str, "file": str}],
            "modules": [{"name": str, "summary": str}],  # from Ollama
            "readme_summary": str | None,                 # from Ollama
            "important_files": [str],
            "total_files": int,
            "total_dirs": int
        }
        """
        prompt = self._build_prompt(facts)
        raw = self._client.complete(prompt, max_tokens=2048)

        if not raw:
            logger.warning("Groq returned no response — using fallback analysis")
            return self._fallback(facts)

        return self._parse_response(raw, facts)

    # ── Prompt construction ───────────────────────────────────────────────────

    def _build_prompt(self, facts: dict) -> str:
        api_lines = "\n".join(
            f"  - {ep.get('method','?')} {ep.get('path','?')} ({ep.get('framework','?')}) [{ep.get('file','')}]"
            for ep in facts.get("apis", [])[:40]
        ) or "  None discovered"

        module_lines = "\n".join(
            f"  - {m['name']}: {m['summary']}"
            for m in facts.get("modules", [])
            if m.get("summary")
        ) or "  No module summaries available"

        readme_section = (
            f"README Summary (generated by local model):\n{facts.get('readme_summary', 'Not available')}"
        )

        patterns = facts.get("notable_patterns", [])
        pattern_lines = "\n".join(f"  - {p}" for p in patterns[:20]) or "  None detected"

        issues_summary = facts.get("issues_summary", {})
        issues_line = (
            ", ".join(f"{count} {sev}-severity" for sev, count in issues_summary.items())
            if issues_summary else "None detected"
        )

        return f"""You are a senior software architect performing a code repository analysis.
You have been given ONLY verified, deterministic facts about this repository.
Do NOT invent features. Do NOT guess based on repository name.
Every claim you make must be justified by the provided evidence.

CRITICAL SPECIFICITY RULES (read before writing any output):
1. Cite specific filenames and directory names from the provided facts wherever possible.
   Instead of "a separate module handles X", write "the `db/` directory handles X" or
   "models.py defines the data layer".
2. When describing architecture patterns or design choices, reference actual detected
   patterns by name and location (e.g. "JWT auth detected in routes/auth.py").
3. Self-check before finalizing each sentence: if the statement could apply to almost
   any backend project without modification, replace it with a more specific one
   grounded in the facts provided below.
4. If you cannot ground a claim in the provided evidence, say
   "Insufficient evidence to determine." — never guess.

Repository: {facts.get('repository_name', 'unknown')}
Files: {facts.get('total_files', 0)} | Directories: {facts.get('total_dirs', 0)}

Technology Stack:
  Frontend:   {', '.join(facts.get('frontend', [])) or 'None detected'}
  Backend:    {', '.join(facts.get('backend', [])) or 'None detected'}
  Databases:  {', '.join(facts.get('databases', [])) or 'None detected'}
  Languages:  {', '.join(facts.get('languages', [])) or 'None detected'}
  Frameworks: {', '.join(facts.get('frameworks', [])) or 'None detected'}

Important Files: {', '.join(facts.get('important_files', [])[:12]) or 'None'}

{readme_section}

Discovered API Endpoints:
{api_lines}

Module Summaries (from local analysis — use these directory/file names in your output):
{module_lines}

Detected Code Patterns (reference these by name and file in architecture notes):
{pattern_lines}

Code Quality Issues Summary: {issues_line}

Based ONLY on the above facts, respond with valid JSON (no markdown, no code fences):
{{
  "project_overview": "2-3 sentences describing what this project does. Cite specific files/directories.",
  "use_case": "One sentence describing the primary use case, based only on evidence.",
  "complexity_level": "Beginner | Intermediate | Advanced",
  "workflow": [
    "Step 1: ...",
    "Step 2: ...",
    "Step 3: ..."
  ],
  "detected_features": [
    {{
      "name": "Feature name (e.g. Authentication, REST API, Database Layer)",
      "evidence": ["specific file or pattern reference", "e.g. JWT auth in routes/auth.py"]
    }}
  ],
  "key_technologies": {{
    "TechName": "Why this technology is used, citing specific files/dirs where detected."
  }},
  "architecture_notes": "2-3 sentences citing specific module names, file names, and detected patterns. Must reference actual names from the facts above — not generic descriptions.",
  "api_summary": "Plain-English summary of the discovered API endpoints, citing specific paths and files.",
  "confidence_score": 85
}}

confidence_score rules:
- 90-100: README + many APIs + clear tech stack + module summaries available
- 70-89:  Some APIs or README, identifiable tech stack
- 50-69:  Tech stack detected but limited API/README evidence
- 0-49:   Very little evidence; heavily flag as low confidence

IMPORTANT: Every architecture_notes sentence must name a specific file, directory, or
detected pattern from the facts above. Generic statements like "the application follows
a layered architecture" without citing specific names are not acceptable."""

    # ── Response parsing ──────────────────────────────────────────────────────

    def _parse_response(self, raw: str, facts: dict) -> dict:
        # Strip markdown code fences if present
        text = raw.strip()
        if text.startswith("```"):
            parts = text.split("```")
            text = parts[1] if len(parts) > 1 else text
            if text.startswith("json"):
                text = text[4:]
            text = text.strip()

        try:
            parsed = json.loads(text)
            # Ensure confidence_score is a float 0-100
            score = parsed.get("confidence_score")
            if isinstance(score, (int, float)):
                parsed["confidence_score"] = max(0.0, min(100.0, float(score)))
            else:
                parsed["confidence_score"] = 50.0

            # Normalise detected_features to list of dicts
            features = parsed.get("detected_features", [])
            if not isinstance(features, list):
                features = []
            parsed["detected_features"] = [
                f if isinstance(f, dict) else {"name": str(f), "evidence": []}
                for f in features
            ]
            logger.info(
                "Groq analysis complete — confidence: %.0f%%",
                parsed["confidence_score"],
            )
            return parsed
        except json.JSONDecodeError:
            logger.warning("Groq returned non-JSON; using raw text as overview")
            return {
                "project_overview": raw[:500],
                "use_case": "See project overview.",
                "complexity_level": "Unknown",
                "workflow": ["Analysis completed. See raw overview above."],
                "detected_features": [],
                "key_technologies": {},
                "architecture_notes": "",
                "api_summary": "",
                "confidence_score": 30.0,
            }

    def _fallback(self, facts: dict) -> dict:
        """Return a minimal analysis when Groq is unavailable."""
        has_apis = bool(facts.get("apis"))
        has_readme = bool(facts.get("readme_summary"))
        score = 40.0 + (20.0 if has_apis else 0) + (15.0 if has_readme else 0)
        return {
            "project_overview": (
                facts.get("readme_summary")
                or "AI analysis unavailable. See technology stack and API inventory for details."
            ),
            "use_case": "See technology stack and API inventory.",
            "complexity_level": "Unknown",
            "workflow": [],
            "detected_features": [],
            "key_technologies": {},
            "architecture_notes": "AI analysis unavailable — architecture notes could not be generated.",
            "api_summary": (
                f"{len(facts.get('apis', []))} API endpoint(s) discovered. See API Inventory for details."
                if has_apis else "No API endpoints discovered."
            ),
            "confidence_score": score,
        }

    def ask_question_with_context(self, prompt: str) -> str:
        """
        Interactive Q&A RAG call.
        Uses dedicated CHAT Groq key if configured.
        """
        from app.services.cloud_llm_service import get_cloud_llm_service
        raw = get_cloud_llm_service().complete(prompt, max_tokens=1024, task_type="chat")
        return raw or "No response from LLM."
